CREATE TABLE IF NOT EXISTS seriesdt (
  SeriesInstanceUID VARCHAR(255) PRIMARY KEY,
  SequenceFileName VARCHAR(255),
  AcquisitionMatrix INTEGER[],
  BodyPartExamined VARCHAR(255),
  FlipAngle VARCHAR(255),
  ImageType VARCHAR(255)[],
  InversionTime NUMERIC,
  NumberOfSeriesRelatedInstances INTEGER,
  OperatorsName VARCHAR(255),
  PAT VARCHAR(255),
  PatientPosition VARCHAR(255),
  PercentPhaseFieldOfView VARCHAR(255),
  ProtocolName VARCHAR(255),
  RepetitionTime VARCHAR(255),
  SOPClassUID VARCHAR(255),
  SeriesDescription VARCHAR(255),
  SeriesNumber INTEGER,
  SeriesTime VARCHAR(255),
  SliceThickness VARCHAR(255),
  SoftwareVersions VARCHAR(255),
  SpacingBetweenSlices NUMERIC,
  StationName VARCHAR(255),
  SeqState VARCHAR(255) DEFAULT 'pending',
  IsSelected BOOLEAN DEFAULT false,
  IsExpanded BOOLEAN DEFAULT false,
  Measured TIMESTAMP DEFAULT NOW(),
  LastUpdated TIMESTAMP DEFAULT NOW(),
  MeasurementNotes TEXT,
  StimProtocol VARCHAR(255),
  StimLogFile VARCHAR(255),
  FyzioRawFile VARCHAR(255),
  GeneralEEG BOOLEAN DEFAULT false,
  GeneralET BOOLEAN DEFAULT false,
  BPEKG BOOLEAN DEFAULT false,
  BPResp BOOLEAN DEFAULT false,
  BPGSR BOOLEAN DEFAULT false,
  BPAcc BOOLEAN DEFAULT false,
  SiemensEKG BOOLEAN DEFAULT false,
  SiemensResp BOOLEAN DEFAULT false,
  SiemensGSR BOOLEAN DEFAULT false,
  SiemensAcc BOOLEAN DEFAULT false
);
